#pragma once
#define MX_INE " IF NOT EXISTS "
#define MX_CREATE(NAME) "CREATE TABLE" MX_INE #NAME " ("
#define MX_INT_PK(NAME) #NAME " INTEGER PRIMARY KEY AUTOINCREMENT,"
#define MX_TRIGGER(NAME, ACT) "CREATE TRIGGER"MX_INE#NAME " AFTER " #ACT " ON "
#define MX_INSERT(TABLE, ...) "INSERT INTO " #TABLE " ("#__VA_ARGS__") VALUES "
#define MX_DEL_WH(TABLE, COND) "DELETE FROM " #TABLE " WHERE " #COND ";"

#define MX_MAKE_REGISTER 1
#define MX_FAILED_REGISTER 2
#define MX_SUCCESS_REGISTER 3

#define MX_MAKE_AUTHORIZATION 4
#define MX_FAILED_AUTHORIZATION 5
#define MX_SUCCESS_AUTHORIZATION 6

#define MX_MAKE_DELETION 7
#define MX_FAILED_DELETION 8
#define MX_SUCCESS_DELETION 9

#define MX_MAKE_CHANGE_PASSWORD 10
#define MX_SUCCESS_CHANGE_PASSWORD 11
#define MX_MAKE_UPDATE_PROFILE 12
#define MX_SUCCESS_UPDATE_PROFILE 13

#define MX_GET_CLIENT_DATA 14
#define MX_GET_CLIENT_CONTACTS 15
#define MX_GET_CLIENT_CHATS 16
#define MX_GET_CLIENT_MESSAGES 17

#define MX_MAKE_NEW_CHAT 18
#define MX_SEND_MESSAGE 19
